### PR TITLE
Simple weapon manager

### PR DESCRIPTION
**Pull request by oscar0pavon**

### CODE REVIEW

**Comment by Sinono3** [comment]
Hey, just saying that I might have to close the request (sorry) because the idea is to have a general items system, not just weapons. And the system will probably have a `WeaponManager` but in many later versions. For now, we will just store the items inside the Creature struct, wait a bit until we can load the creatures from JSON files and the will get work started on the items.

**Comment by Sinono3** [comment]
Also, we will have a `Vec<Item>` on the game state anyways, so `available_weapons` wouldn't really be needed in this case.

**Comment by oscarpavon** [comment]
Ok, ahi te escribi en el facebook

________________________________

**Comment by oscar0pavon** [comment]
So, what next?

________________________________

**Comment by Sinono3** [comment]
JSON file loading to `Creature`.

**Comment by oscar0pavon** [comment]
researching..
________________________________

**Comment by Sinono3** [comment]
Just saying that I'm planning on use serde.js, so I reccommend you research that.

**Pull request closed without merging**
